# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Zhelun Chen's Portfolio
description: A personal portfolio and blog by Zhelun Chen.
baseurl: ""
url: https://zhelunchen.github.io

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Zhelun "Aaron" Chen, PhD
  description:
    - Hello!
    - This tiny website
    - Looks like json
  cv: assets/cv.pdf
  where:
    - Drexel University
    - Philadelphia, PA, USA
  contact:
    phone: +1 412 230 7189
    email: zl.chen.career@gmail.com
  profiles:
    linkedin: https://www.linkedin.com/in/zhelun/
    github: https://github.com/ZhelunChen

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
